//@version=5
indicator("Bollinger Bands", shorttitle="BB", overlay=true)
length = input(20, title="Length")
src = input(close, title="Source")
mult = input(2.0, title="Multiplier")
basis = ta.sma(src, length)
dev = mult * ta.stdev(src, length)
upper = basis + dev
lower = basis - dev
p1 = plot(basis, color=color.blue, title="Basis")
p2 = plot(upper, color=color.green, title="Upper Band")
p3 = plot(lower, color=color.red, title="Lower Band")
fill(p2, p3, color=color.purple, transp=90, title="Background")


